/**
 * Dados Mock do Sistema SGCS
 * Tipados com as interfaces de @/types
 */
import type {
  Penalidade,
  Prorrogacao,
  FornecedorCombobox,
  Processo,
  RequisicaoCompra,
} from "@/types";

// ============================================================
// Penalidades
// ============================================================
export const penalidades: Penalidade[] = [
  {
    id: 1,
    empresa: "Empresa ABC Ltda",
    processo: "2024-001",
    penalidade: "Atraso na entrega",
    multa: "R$ 12.500,00",
    valor: "R$ 12.500,00",
    notificacoes: 2,
    status: "Ativo",
    dataOcorrencia: "15/01/2024",
    dataAplicacao: "20/01/2024",
    dataVencimento: "20/03/2025",
    responsavel: "Maria Silva",
  },
  {
    id: 2,
    empresa: "Serviços DEF Eireli",
    processo: "2024-003",
    penalidade: "Abandono de serviço",
    multa: "R$ 45.200,00",
    valor: "R$ 45.200,00",
    notificacoes: 3,
    status: "Ativo",
    dataOcorrencia: "08/01/2024",
    dataAplicacao: "10/01/2024",
    dataVencimento: "10/04/2025",
    responsavel: "Ana Costa",
  },
  {
    id: 3,
    empresa: "Tecnologia GHI Ltda",
    processo: "2024-005",
    penalidade: "Descumprimento contratual",
    multa: "R$ 28.300,00",
    valor: "R$ 28.300,00",
    notificacoes: 1,
    status: "Ativo",
    dataOcorrencia: "22/02/2024",
    dataAplicacao: "25/02/2024",
    dataVencimento: "25/05/2025",
    responsavel: "Carlos Oliveira",
  },
  {
    id: 4,
    empresa: "Comércio JKL Ltda",
    processo: "2023-075",
    penalidade: "Atraso na entrega",
    multa: "R$ 15.300,00",
    valor: "R$ 15.300,00",
    notificacoes: 2,
    status: "Aplicada",
    dataOcorrencia: "10/12/2023",
    dataAplicacao: "15/12/2023",
    dataVencimento: "15/12/2024",
    dataEncerramento: "20/12/2024",
    responsavel: "Pedro Alves",
  },
  {
    id: 5,
    empresa: "Construções PQR Ltda",
    processo: "2024-010",
    penalidade: "Atraso na entrega",
    multa: "R$ 22.000,00",
    valor: "R$ 22.000,00",
    notificacoes: 3,
    status: "Vencida",
    dataOcorrencia: "01/06/2024",
    dataAplicacao: "05/06/2024",
    dataVencimento: "15/12/2024",
    responsavel: "Ricardo Sousa",
  },
  {
    id: 6,
    empresa: "Alimentos STU S.A",
    processo: "2024-012",
    penalidade: "Produto fora de especificação",
    multa: "R$ 31.700,00",
    valor: "R$ 31.700,00",
    notificacoes: 2,
    status: "Vencida",
    dataOcorrencia: "10/07/2024",
    dataAplicacao: "15/07/2024",
    dataVencimento: "15/01/2025",
    responsavel: "Paula Mendes",
  },
];

// ============================================================
// Prorrogações
// ============================================================
export const prorrogacoes: Prorrogacao[] = [
  {
    id: 1,
    empresa: "Empresa ABC Ltda",
    contrato: "SCA-2024-001",
    objetoContrato: "Serviços de Manutenção Predial e Conservação",
    cnpjCpf: "12.345.678/0001-90",
    numeroProcesso: "PROC-2024-001",
    valorContratadoAnual: "R$ 250.000,00",
    dataInicio: "15/01/2024",
    dataFimOriginal: "15/07/2024",
    dataFimProrrogada: "15/10/2024",
    prazoOriginal: "6 meses",
    prazoProrrogacao: "9 meses",
    quantidadeAditivos: 1,
    passivelProrrogar: true,
    status: "Vigente",
    motivo: "Necessidade de conclusão de etapas pendentes",
    dataSolicitacao: "10/06/2024",
    responsavel: "Maria Silva",
    historicoProrrogacoes: [
      {
        aditivo: "1º Aditivo",
        dataInicio: "15/07/2024",
        dataFim: "15/10/2024",
        observacoes: "Necessidade de conclusão de etapas pendentes do projeto.",
      },
    ],
  },
  {
    id: 2,
    empresa: "Fornecedor XYZ S.A",
    contrato: "SCA-2023-089",
    objetoContrato: "Fornecimento de Equipamentos de TI e Suporte Técnico",
    cnpjCpf: "98.765.432/0001-10",
    numeroProcesso: "PROC-2023-089",
    valorContratadoAnual: "R$ 480.000,00",
    dataInicio: "20/08/2023",
    dataFimOriginal: "20/02/2024",
    dataFimProrrogada: "20/05/2024",
    prazoOriginal: "6 meses",
    prazoProrrogacao: "9 meses",
    quantidadeAditivos: 1,
    passivelProrrogar: false,
    status: "Encerrado",
    motivo: "Atraso na entrega de equipamentos",
    dataSolicitacao: "15/01/2024",
    responsavel: "João Santos",
    historicoProrrogacoes: [
      {
        aditivo: "1º Aditivo",
        dataInicio: "20/02/2024",
        dataFim: "20/05/2024",
        observacoes: "Prorrogação devido a atrasos na importação.",
      },
    ],
  },
  {
    id: 3,
    empresa: "Serviços DEF Eireli",
    contrato: "SCA-2024-015",
    objetoContrato: "Prestação de Serviços de Limpeza e Conservação",
    cnpjCpf: "23.456.789/0001-22",
    numeroProcesso: "PROC-2024-015",
    valorContratadoAnual: "R$ 180.000,00",
    dataInicio: "01/03/2024",
    dataFimOriginal: "01/09/2024",
    dataFimProrrogada: "01/12/2024",
    prazoOriginal: "6 meses",
    prazoProrrogacao: "9 meses",
    quantidadeAditivos: 1,
    passivelProrrogar: true,
    status: "Próximo ao Vencimento",
    motivo: "Bom desempenho do fornecedor",
    dataSolicitacao: "15/08/2024",
    responsavel: "Ana Costa",
    historicoProrrogacoes: [
      {
        aditivo: "1º Aditivo",
        dataInicio: "01/09/2024",
        dataFim: "01/12/2024",
        observacoes: "Prorrogação por bom desempenho do fornecedor.",
      },
    ],
  },
];

// ============================================================
// Fornecedores para Combobox
// ============================================================
export const fornecedoresComCNPJ: FornecedorCombobox[] = [
  { value: "empresa-abc-ltda", label: "Empresa ABC Ltda", cnpj: "12.345.678/0001-90", categoria: "Manutenção" },
  { value: "fornecedor-xyz-sa", label: "Fornecedor XYZ S.A", cnpj: "98.765.432/0001-10", categoria: "Tecnologia" },
  { value: "servicos-def-eireli", label: "Serviços DEF Eireli", cnpj: "23.456.789/0001-22", categoria: "Serviços" },
  { value: "tecnologia-ghi-ltda", label: "Tecnologia GHI Ltda", cnpj: "34.567.890/0001-33", categoria: "Tecnologia" },
  { value: "comercio-jkl-ltda", label: "Comércio JKL Ltda", cnpj: "45.678.901/0001-44", categoria: "Comércio" },
  { value: "distribuidora-mno-sa", label: "Distribuidora MNO S.A", cnpj: "56.789.012/0001-55", categoria: "Distribuição" },
  { value: "solucoes-pqr-corp", label: "Soluções PQR Corp", cnpj: "67.890.123/0001-66", categoria: "Consultoria" },
  { value: "industria-stu-ltda", label: "Indústria STU Ltda", cnpj: "78.901.234/0001-77", categoria: "Indústria" },
  { value: "construtora-vwx-sa", label: "Construtora VWX S.A", cnpj: "89.012.345/0001-88", categoria: "Construção" },
  { value: "logistica-yza-eireli", label: "Logística YZA Eireli", cnpj: "90.123.456/0001-99", categoria: "Logística" },
];

// ============================================================
// Processos (mock para Comprador)
// ============================================================
export const processosComprador: Processo[] = [
  {
    id: "PROC-2024-001",
    descricao: "Aquisição de Equipamentos de TI",
    modalidade: "Pregão Eletrônico",
    empresa: "Fornecedor XYZ S.A",
    status: "Finalizado",
    responsavel: "João Santos",
    prioridade: "Alta",
    dataDistribuicao: "10/01/2024",
    dataAprovacao: "20/01/2024",
    valor: "R$ 450.000,00",
  },
  {
    id: "PROC-2024-002",
    descricao: "Contratação de Serviços de Limpeza",
    modalidade: "Dispensa",
    empresa: "Serviços DEF Eireli",
    status: "Aprovado",
    responsavel: "João Santos",
    prioridade: "Média",
    dataDistribuicao: "15/01/2024",
    dataAprovacao: "22/01/2024",
    valor: "R$ 180.000,00",
  },
  {
    id: "PROC-2024-003",
    descricao: "Aquisição de Mobiliário",
    modalidade: "Licitação",
    empresa: "Comércio JKL Ltda",
    status: "Finalizado",
    responsavel: "João Santos",
    prioridade: "Baixa",
    dataDistribuicao: "20/01/2024",
    dataAprovacao: "03/03/2024",
    valor: "R$ 95.000,00",
  },
  {
    id: "PROC-2024-004",
    descricao: "Serviços de Consultoria Especializada",
    modalidade: "Inexigibilidade",
    empresa: "Soluções PQR Corp",
    status: "Aprovado",
    responsavel: "João Santos",
    prioridade: "Alta",
    dataDistribuicao: "25/01/2024",
    dataAprovacao: "28/01/2024",
    valor: "R$ 350.000,00",
  },
  {
    id: "PROC-2024-005",
    descricao: "Material de Escritório",
    modalidade: "Dispensa",
    empresa: "Comércio JKL Ltda",
    status: "Finalizado",
    responsavel: "João Santos",
    prioridade: "Baixa",
    dataDistribuicao: "01/02/2024",
    dataAprovacao: "10/02/2024",
    valor: "R$ 25.000,00",
  },
  {
    id: "PROC-2024-006",
    descricao: "Contratação de Serviços de Manutenção",
    modalidade: "Pregão Eletrônico",
    empresa: "Empresa ABC Ltda",
    status: "Finalizado",
    responsavel: "João Santos",
    prioridade: "Média",
    dataDistribuicao: "05/02/2024",
    dataAprovacao: "15/03/2024",
    valor: "R$ 250.000,00",
  },
  {
    id: "PROC-2024-007",
    descricao: "Aquisição de Uniformes Operacionais",
    modalidade: "Pregão Eletrônico",
    empresa: "Indústria STU Ltda",
    status: "Aprovado",
    responsavel: "Ana Costa",
    prioridade: "Média",
    dataDistribuicao: "12/02/2024",
    dataAprovacao: "30/03/2024",
    valor: "R$ 132.000,00",
  },
  {
    id: "PROC-2024-008",
    descricao: "Licenças de Software de Gestão",
    modalidade: "Inexigibilidade",
    empresa: "Tecnologia GHI Ltda",
    status: "Finalizado",
    responsavel: "Carlos Oliveira",
    prioridade: "Alta",
    dataDistribuicao: "16/02/2024",
    dataAprovacao: "20/02/2024",
    valor: "R$ 89.900,00",
  },
  {
    id: "PROC-2024-009",
    descricao: "Reforma do Espaço de Atendimento",
    modalidade: "Licitação",
    empresa: "Construtora VWX S.A",
    status: "Aprovado",
    responsavel: "Maria Silva",
    prioridade: "Alta",
    dataDistribuicao: "18/02/2024",
    dataAprovacao: "20/06/2024",
    valor: "R$ 980.000,00",
  },
  {
    id: "PROC-2024-010",
    descricao: "Fornecimento de Gêneros Alimentícios",
    modalidade: "Pregão Eletrônico",
    empresa: "Alimentos STU S.A",
    status: "Em Cotação",
    responsavel: "Paula Mendes",
    prioridade: "Alta",
    dataDistribuicao: "25/02/2024",
    valor: "R$ 410.000,00",
  },
  {
    id: "PROC-2024-011",
    descricao: "Locação de Equipamentos Audiovisuais",
    modalidade: "Dispensa",
    empresa: "Logística YZA Eireli",
    status: "Em Análise",
    responsavel: "Ana Costa",
    prioridade: "Média",
    dataDistribuicao: "01/03/2024",
    valor: "R$ 58.000,00",
  },
  {
    id: "PROC-2024-012",
    descricao: "Serviço de Jardinagem e Paisagismo",
    modalidade: "Dispensa",
    empresa: "Serviços DEF Eireli",
    status: "Aguardando Documentação",
    responsavel: "Carlos Oliveira",
    prioridade: "Baixa",
    dataDistribuicao: "04/03/2024",
    valor: "R$ 32.000,00",
  },
  {
    id: "PROC-2024-013",
    descricao: "Implantação de Sistema de CFTV",
    modalidade: "Licitação",
    empresa: "Tecnologia GHI Ltda",
    status: "Finalizado",
    responsavel: "Maria Silva",
    prioridade: "Alta",
    dataDistribuicao: "08/03/2024",
    dataAprovacao: "22/04/2024",
    valor: "R$ 265.000,00",
  },
  {
    id: "PROC-2024-014",
    descricao: "Aquisição de Materiais Pedagógicos",
    modalidade: "Pregão Eletrônico",
    empresa: "Comércio JKL Ltda",
    status: "Aprovado",
    responsavel: "João Santos",
    prioridade: "Média",
    dataDistribuicao: "10/03/2024",
    dataAprovacao: "25/03/2024",
    valor: "R$ 147.500,00",
  },
  {
    id: "PROC-2024-015",
    descricao: "Contratação de Empresa de Segurança",
    modalidade: "Licitação",
    empresa: "Empresa ABC Ltda",
    status: "Rejeitado",
    responsavel: "Paula Mendes",
    prioridade: "Alta",
    dataDistribuicao: "15/03/2024",
    valor: "R$ 520.000,00",
  },
  {
    id: "PROC-2024-016",
    descricao: "Consultoria para Transformação Digital",
    modalidade: "Inexigibilidade",
    empresa: "Soluções PQR Corp",
    status: "Aprovado",
    responsavel: "Carlos Oliveira",
    prioridade: "Média",
    dataDistribuicao: "18/03/2024",
    dataAprovacao: "12/04/2024",
    valor: "R$ 198.000,00",
  },
  {
    id: "PROC-2024-017",
    descricao: "Renovação de Contrato de Internet Dedicada",
    modalidade: "Dispensa",
    empresa: "Fornecedor XYZ S.A",
    status: "Finalizado",
    responsavel: "Ana Costa",
    prioridade: "Baixa",
    dataDistribuicao: "22/03/2024",
    dataAprovacao: "24/03/2024",
    valor: "R$ 44.000,00",
  },
  {
    id: "PROC-2024-018",
    descricao: "Serviço de Manutenção de Elevadores",
    modalidade: "Inexigibilidade",
    empresa: "Empresa ABC Ltda",
    status: "Devolvido ao Requisitante",
    responsavel: "Maria Silva",
    prioridade: "Média",
    dataDistribuicao: "25/03/2024",
    valor: "R$ 76.300,00",
    justificativaDevolucao: "Necessário complementar especificações técnicas e plano de execução.",
  },
  {
    id: "PROC-2024-019",
    descricao: "Aquisição de Veículos Utilitários",
    modalidade: "Pregão Eletrônico",
    empresa: "Distribuidora MNO S.A",
    status: "Finalizado",
    responsavel: "João Santos",
    prioridade: "Alta",
    dataDistribuicao: "28/03/2024",
    dataAprovacao: "25/07/2024",
    valor: "R$ 1.240.000,00",
  },
  {
    id: "PROC-2024-020",
    descricao: "Fornecimento de Materiais de Limpeza",
    modalidade: "Dispensa",
    empresa: "Serviços DEF Eireli",
    status: "Rejeitada",
    responsavel: "Paula Mendes",
    prioridade: "Baixa",
    dataDistribuicao: "30/03/2024",
    valor: "R$ 22.400,00",
  },
];

// ============================================================
// Requisições de Compra (mock para Requisitante)
// ============================================================
export const requisicoesCompra: RequisicaoCompra[] = [
  {
    id: "RC-2024-0147",
    objeto: "Computadores Desktop para Setor Administrativo",
    descricao: "Aquisição de 15 computadores desktop para renovação do parque tecnológico do setor administrativo.",
    dataRequisicao: "10/01/2024",
    status: "Em cotação",
    responsavelAtual: "João Santos",
    departamento: "Administrativo",
    solicitante: "Maria Requisitante",
  },
  {
    id: "RC-2024-0152",
    objeto: "Material de Escritório - Ressuprimento Trimestral",
    descricao: "Ressuprimento trimestral de materiais de escritório para todos os setores.",
    dataRequisicao: "15/01/2024",
    status: "Aprovada",
    responsavelAtual: "Ana Costa",
    departamento: "Suprimentos",
    solicitante: "Maria Requisitante",
  },
  {
    id: "RC-2024-0165",
    objeto: "Licenças de Software Antivírus",
    descricao: "Renovação de licenças de software antivírus para 200 estações.",
    dataRequisicao: "22/01/2024",
    status: "Análise de RC",
    responsavelAtual: "Carlos Oliveira",
    departamento: "TI",
    solicitante: "Maria Requisitante",
  },
  {
    id: "RC-2024-0178",
    objeto: "Cadeiras Ergonômicas",
    descricao: "Aquisição de cadeiras ergonômicas para o setor de atendimento.",
    dataRequisicao: "28/01/2024",
    status: "Devolvido ao Requisitante",
    responsavelAtual: "Maria Silva",
    departamento: "Atendimento",
    solicitante: "Maria Requisitante",
  },
  {
    id: "RC-2024-0190",
    objeto: "Serviço de Manutenção de Ar Condicionado",
    descricao: "Contratação de serviço de manutenção preventiva dos aparelhos de ar condicionado.",
    dataRequisicao: "05/02/2024",
    status: "Finalizado",
    responsavelAtual: "Pedro Alves",
    departamento: "Manutenção",
    solicitante: "Maria Requisitante",
  },
];

// ============================================================
// Funções de cálculo
// ============================================================

/** Calcula alertas de penalidades vencidas */
export function calcularAlertasPenalidades(): {
  total: number;
  descricao: string;
} {
  const penalidadesVencidas = penalidades.filter(
    (p) => p.status === "Vencida"
  );
  return {
    total: penalidadesVencidas.length,
    descricao: "Requer atenção imediata",
  };
}

/** Calcula alertas de prorrogações */
export function calcularAlertasProrrogacoes(): {
  total: number;
  vencendoEm30Dias: number;
  descricao: string;
} {
  const contratosVencendo = prorrogacoes.filter(
    (p) => p.status === "Vencendo"
  );
  return {
    total: prorrogacoes.length,
    vencendoEm30Dias: contratosVencendo.length,
    descricao: `${contratosVencendo.length} vencendo em 30 dias`,
  };
}
